### ISSUE TITLE
Separation character does not display properly

### ISSUE THREAD

**Issue by allefeld** [curly210102/vscode-markdown-word-count#3]
When `markdown-word-count.selectionCount` is activated, both the selection and the total count are shown in the status bar and the popup. However, the character separating the two counts does not display properly on my system:

![image](https://user-images.githubusercontent.com/1738353/226462360-effe4156-b218-4438-8202-dccf01715673.png)

The character "／" appears to be U+FF0F FULLWIDTH SOLIDUS. While that is a good choice in principle, it does not appear to be present in the default VS Code UI font on Linux, Noto Sans.

I recommend to use the standard ASCII slash, aka  "/" U+002F SOLIDUS instead.

**Comment by curly210102** [comment]
Thanks for feedback, this issue is fixed with version 0.0.7

**Comment by allefeld** [comment]
Great, thank you!
