### ISSUE TITLE
Support VS Code for Web also

### ISSUE THREAD

**Issue by sohang3112** [curly210102/vscode-markdown-word-count#4]
Currently this extension can't be installed on [VS Code for Web](https://github.dev) - there it shows this error *The 'Markdown Word Count' extension is not available in Visual Studio Code for the Web.* 
 
 Please add support for VS Code for Web also. This is especially useful while editing Markdown pages online for a Github Pages site.

**Comment by curly210102** [comment]
Thanks for feedback, this extension now supports VSCode for Web.

**Comment by sohang3112** [comment]
@curly210102 Thanks for implementing this 🙂
